### ISSUE TITLE
Parse Golang dependencies

### ISSUE THREAD

**Issue by micfan** [PCF-License/license_auto#3]
``` bash
$ go list -json ./...
```
* [Google groups: List external dependencies of package](https://groups.google.com/forum/#!topic/golang-nuts/611QEJqkDKw)
* https://github.com/golang/go/wiki/InstallTroubleshooting
* https://golang.org/cmd/go/#hdr-List_packages
* https://github.com/tools/godep
* https://github.com/cespare/deplist

**Comment by CissyHao** [comment]
go list -f '{{.Deps}}' ./... | tr "[" " " | tr "]" " " | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}'
