### ISSUE TITLE
Parse Ruby dependencies & detect their LicenseInfo

### ISSUE THREAD

**Issue by micfan** [PCF-License/license_auto#4]
seek help from @micfan 's database design

* Query local database first.
* mark as `unknonw` into license column if the official site does offer a info of license.
* [Gemfile details](http://bundler.io/gemfile.html)
* [RESTful API](http://guides.rubygems.org/rubygems-org-api/)
* https://github.com/rubygems/gems

**Comment by micfan** [comment]
RESTful API http://guides.rubygems.org/rubygems-org-api/

**Comment by yulilong** [comment]
RESTful API completed.
